import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const url = (process.env.AUTO_SWAP_SUPABASE_URL || '').trim();
const anonKey = (process.env.AUTO_SWAP_SUPABASE_ANON_KEY || '').trim();

if (!url || !anonKey) {
  console.error('gen-config: AUTO_SWAP_SUPABASE_URL and AUTO_SWAP_SUPABASE_ANON_KEY are required.');
  process.exit(1);
}

if (/^sb_secret_/i.test(anonKey)) {
  console.error('gen-config: refusing a secret key (sb_secret_...): use the publishable key (sb_publishable_...).');
  process.exit(1);
}

if (!/^sb_publishable_/i.test(anonKey)) {
  try {
    const payload = JSON.parse(Buffer.from(anonKey.split('.')[1] || '', 'base64url').toString());
    if (payload.role && payload.role !== 'anon') {
      console.error(`gen-config: refusing a "${payload.role}" key: use the public anon key only.`);
      process.exit(1);
    }
  } catch {  }
}

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, '..', 'front', 'supabase-config.js');
const body = `// Generated by scripts/gen-config.mjs at build time, do not edit by hand.
window.AUTO_SWAP_SUPABASE_URL = ${JSON.stringify(url)};
window.AUTO_SWAP_SUPABASE_ANON_KEY = ${JSON.stringify(anonKey)};
`;
writeFileSync(out, body);
console.log(`gen-config: wrote ${out}`);
