// Generate front/supabase-config.js from environment variables at deploy time.
// The config file is gitignored (it is environment-specific), so the static
// host must materialize it during the build. Run as the build command:
//
//   AUTO_SWAP_SUPABASE_URL=... AUTO_SWAP_SUPABASE_ANON_KEY=... node scripts/gen-config.mjs
//
// Only the public anon key belongs here — never the service-role key.
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const url = (process.env.AUTO_SWAP_SUPABASE_URL || '').trim();
const anonKey = (process.env.AUTO_SWAP_SUPABASE_ANON_KEY || '').trim();

if (!url || !anonKey) {
  console.error('gen-config: AUTO_SWAP_SUPABASE_URL and AUTO_SWAP_SUPABASE_ANON_KEY are required.');
  process.exit(1);
}

// Newer projects issue sb_publishable_… / sb_secret_… instead of JWTs. Those are
// not parseable as JWTs, so the check below silently passed them through and a
// secret key could have been written into browser code.
if (/^sb_secret_/i.test(anonKey)) {
  console.error('gen-config: refusing a secret key (sb_secret_…) — use the publishable key (sb_publishable_…).');
  process.exit(1);
}

// Reject an accidental service-role key (its JWT payload carries role:service_role).
if (!/^sb_publishable_/i.test(anonKey)) {
  try {
    const payload = JSON.parse(Buffer.from(anonKey.split('.')[1] || '', 'base64url').toString());
    if (payload.role && payload.role !== 'anon') {
      console.error(`gen-config: refusing a "${payload.role}" key — use the public anon key only.`);
      process.exit(1);
    }
  } catch { /* not a JWT we can parse; let the frontend's own guard catch it */ }
}

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, '..', 'front', 'supabase-config.js');
const body = `// Generated by scripts/gen-config.mjs at build time — do not edit by hand.
window.AUTO_SWAP_SUPABASE_URL = ${JSON.stringify(url)};
window.AUTO_SWAP_SUPABASE_ANON_KEY = ${JSON.stringify(anonKey)};
`;
writeFileSync(out, body);
console.log(`gen-config: wrote ${out}`);
